version: "3"

services:
  drzl-pg:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"
    volumes:
      - drzl-pg-data:/var/lib/postgres

    networks:
      - auths-network

  drzl-redis:
    image: redis:latest

    ports:
      - "6379:6379"
    volumes:
      - drzl-redis-data:/data

    networks:
      - auths-network

networks:
  auths-network:
    driver: bridge
volumes:
  drzl-pg-data:
  drzl-redis-data:
  node_modules:
